const plans=[{day:'Senin',name:'Push',desc:'Dada · bahu · triceps',time:'60–70 menit',ex:[['Incline Smith Press',3,'6–10','Compound'],['Dumbbell Shoulder Press',3,'8–12','Compound'],['Seated Chest Fly',3,'10–15','Isolation'],['Cable Lateral Raise',3,'12–20','Isolation'],['Overhead Triceps Extension',3,'10–15','Isolation'],['Triceps Pushdown',3,'10–15','Isolation'],['Cable Crunch',3,'10–15','Core']]},{day:'Rabu',name:'Pull',desc:'Punggung · bahu belakang · biceps',time:'60–70 menit',ex:[['Lat Pulldown',3,'8–12','Compound'],['Seated Cable Row',3,'8–12','Compound'],['Chest-Supported Row / Machine Row',3,'8–12','Compound'],['Reverse Pec Deck Fly',3,'12–20','Isolation'],['Barbell Curl',3,'8–12','Isolation'],['Dumbbell Hammer Curl',3,'10–15','Isolation'],['Hanging Knee Raise',3,'10–15','Core']]},{day:'Kamis',name:'Legs',desc:'Paha · hamstring · betis',time:'65–80 menit',ex:[['Hack Squat',3,'6–10','Compound'],['Romanian Deadlift (RDL)',3,'8–12','Compound'],['Leg Press',3,'8–12','Compound'],['Leg Extension',3,'10–15','Isolation'],['Seated Hamstring Curl',3,'10–15','Isolation'],['Calf Raise',3,'12–20','Isolation'],['Cable Crunch / Ab Machine',3,'10–15','Core']]}];
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`},fmt=d=>new Date(d+'T12:00:00').toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'}),setCounts=plans.map(p=>p.ex.map(e=>e[1]));
let db={sessions:{}},selected=({1:0,3:1,4:2})[new Date().getDay()]??0,date=localDate(),deleted=null,timerId,timerEnds=0,toastId,toastHideId,undoId;
try{const raw=localStorage.getItem('lift-log-v1'),saved=raw&&normalizeDb(JSON.parse(raw),setCounts);if(saved)db=saved;else if(raw)$('notice').textContent='Sebagian data lama tidak valid. Data asli tetap tersimpan; ekspor cadangan sebelum membuat perubahan.'}catch(e){$('notice').textContent='Catatan tidak dapat dibaca. Data lama tidak ditimpa sampai kamu membuat perubahan.'}
$('date').value=date;$('today').textContent=new Date().toLocaleDateString('id-ID',{weekday:'short',day:'numeric',month:'short'});
function toast(message,type='success',duration=3000){clearTimeout(toastId);clearTimeout(toastHideId);const el=$('toast');el.className=`toast ${type}`;el.hidden=false;$('toast-icon').textContent=type==='error'?'!':'✓';$('toast-message').textContent=message;toastId=setTimeout(()=>{el.classList.add('hiding');toastHideId=setTimeout(()=>{el.hidden=true;el.classList.remove('hiding')},180)},duration)}
function key(){return `${date}_${selected}`}
function blank(){return {date,plan:selected,sets:plans[selected].ex.map(e=>Array.from({length:e[1]},()=>({kg:'',reps:'',rir:'',done:false}))),notes:'',finished:false}}
function session(){return db.sessions[key()]||blank()}
function persist(){try{const raw=localStorage.getItem('lift-log-v1');if(raw&&!localStorage.getItem('lift-log-v1-backup'))localStorage.setItem('lift-log-v1-backup',raw);localStorage.setItem('lift-log-v1',JSON.stringify(db));return true}catch(e){const message='Penyimpanan browser tidak tersedia atau penuh. Perubahan terbaru belum tersimpan.';$('notice').textContent=message;toast(message,'error',5000);return false}}
function save(s,message='Perubahan tersimpan.'){db.sessions[key()]=s;if(persist())toast(message);stats()}
function previous(name){return Object.values(db.sessions).filter(s=>s.date<date&&plans[s.plan]).sort((a,b)=>b.date.localeCompare(a.date)).map(s=>{const i=plans[s.plan].ex.findIndex(e=>e[0]===name),sets=s.sets[i]?.filter(x=>x.done);return i<0||!sets?.length?null:{date:s.date,sets}}).find(Boolean)}
function stats(){const ss=Object.values(db.sessions),done=ss.filter(s=>s.finished).length,sets=ss.reduce((n,s)=>n+s.sets.flat().filter(x=>x.done).length,0),volume=ss.reduce((n,s)=>n+s.sets.flat().reduce((t,x)=>t+(x.done?Number(x.kg)*Number(x.reps):0),0),0);$('stats').innerHTML=`<div class="stat"><small>SESI SELESAI</small><strong>${done}<span>sesi</span></strong></div><div class="stat"><small>SET TERCATAT</small><strong>${sets}<span>set</span></strong></div><div class="stat"><small>TOTAL VOLUME</small><strong>${volume.toLocaleString('id-ID')}<span>kg × reps</span></strong></div>`}
function progress(){const s=session(),total=s.sets.flat().length,done=s.sets.flat().filter(x=>x.done).length;$('completion').textContent=`${done} / ${total} set selesai`;$('progress-fill').style.width=done/total*100+'%';const bar=$('progress-fill').parentElement;bar.setAttribute('aria-valuenow',done);bar.setAttribute('aria-valuemax',total);$('finish').textContent=s.finished?'Sesi selesai ✓':'Selesaikan sesi'}
function render(){const p=plans[selected],s=session();$('week').innerHTML=plans.map((plan,i)=>`<button class="day ${selected===i?'selected':''}" data-plan="${i}" aria-pressed="${selected===i}"><b>0${i+1}</b><span>${plan.day}<small>${plan.name} · ${plan.ex.length} latihan</small></span></button>`).join('');$('day-label').textContent=`${p.day.toUpperCase()} / ${p.time.toUpperCase()}`;$('session-title').textContent=p.name+' day';$('session-desc').textContent=p.desc;$('notes').value=s.notes;$('exercises').innerHTML=p.ex.map((e,i)=>{const prev=previous(e[0]);return `<article class="exercise"><div class="exercise-info"><span class="number">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(e[0])}</h3><p class="meta">${e[1]} set × ${e[2]} reps · ${e[3]==='Compound'?'2–3 menit rest':'60–90 detik rest'}</p><div class="exercise-actions"><span class="tag">${e[3]}</span><button type="button" class="move-button" data-guide="${esc(e[0])}"><span aria-hidden="true">▧</span><span>Cara gerakan</span></button>${prev?`<button type="button" class="copy-button" data-copy="${i}">Salin set terakhir</button>`:''}</div><p class="previous">${prev?'Terakhir '+fmt(prev.date)+': '+prev.sets.map(x=>(x.kg||0)+' kg × '+x.reps).join(' · '):'Belum ada catatan sebelumnya'}</p></div></div><div class="sets"><div class="set-head"><span>SET</span><span>BEBAN (KG)</span><span>REPS</span><span>RIR</span><span>DONE</span></div>${s.sets[i].map((x,j)=>`<div class="set-row"><span>${j+1}</span><input type="number" min="0" max="2000" step="0.5" inputmode="decimal" placeholder="0" value="${esc(x.kg)}" data-ex="${i}" data-set="${j}" data-field="kg" aria-label="${esc(e[0])} set ${j+1} beban kg"><input type="number" min="1" max="1000" step="1" inputmode="numeric" placeholder="${e[2]}" value="${esc(x.reps)}" data-ex="${i}" data-set="${j}" data-field="reps" aria-label="${esc(e[0])} set ${j+1} repetisi"><select data-ex="${i}" data-set="${j}" data-field="rir" aria-label="${esc(e[0])} set ${j+1} RIR"><option value="">—</option>${[0,1,2,3,4,5].map(r=>`<option value="${r}" ${String(x.rir)===String(r)?'selected':''}>${r}${r===5?'＋':''}</option>`).join('')}</select><button class="check ${x.done?'checked':''}" data-check="${i},${j}" aria-pressed="${x.done}" aria-label="Tandai ${esc(e[0])} set ${j+1} selesai">✓</button></div>`).join('')}</div></article>`}).join('');progress()}
function startTimer(seconds){clearInterval(timerId);timerEnds=Date.now()+seconds*1000;$('rest-timer').hidden=false;updateTimer();timerId=setInterval(updateTimer,1000)}
function updateTimer(){const left=Math.max(0,Math.ceil((timerEnds-Date.now())/1000));$('timer-time').textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`;if(!left){clearInterval(timerId);$('timer-label').textContent='Istirahat selesai';toast('Waktu istirahat selesai.')}}
$('timer-close').onclick=()=>{clearInterval(timerId);timerEnds=0;$('rest-timer').hidden=true;$('timer-label').textContent='Waktu istirahat';$('timer-time').textContent='0:00';toast('Timer dihentikan.')};
$('week').onclick=e=>{const b=e.target.closest('[data-plan]');if(b){selected=Number(b.dataset.plan);render()}};
$('date').onchange=e=>{if(!e.target.value){e.target.value=date;return}date=e.target.value;render()};
$('exercises').oninput=e=>{const t=e.target;if(!t.dataset.field)return;const val=t.value,isRir=t.dataset.field==='rir';if(val!==''&&(!Number.isFinite(Number(val))||Number(val)<0||Number(val)>(isRir?5:Number(t.max))||((t.dataset.field==='reps'||isRir)&&!Number.isInteger(Number(val)))||(t.dataset.field==='kg'&&Number(val)*2%1!==0))){t.setCustomValidity('Masukkan angka dalam batas dan kelipatan yang valid');t.reportValidity();return}t.setCustomValidity('');const s=session();s.sets[t.dataset.ex][t.dataset.set][t.dataset.field]=val;s.finished=false;db.sessions[key()]=s;persist();stats();progress()};
$('exercises').onclick=e=>{const copy=e.target.closest('[data-copy]');if(copy){const i=Number(copy.dataset.copy),prev=previous(plans[selected].ex[i][0]);if(prev){const s=session();prev.sets.slice(0,s.sets[i].length).forEach((set,j)=>{s.sets[i][j]={kg:set.kg,reps:set.reps,rir:'',done:false}});save(s,'Set terakhir disalin.');render()}return}const b=e.target.closest('[data-check]');if(!b)return;const [i,j]=b.dataset.check.split(',').map(Number),s=session(),x=s.sets[i][j];if(!x.done&&(!x.reps||Number(x.reps)<1)){$('notice').textContent='Isi jumlah repetisi sebelum menandai set selesai.';toast('Isi repetisi sebelum menyelesaikan set.','error');return}x.done=!x.done;s.finished=false;save(s,x.done?'Set selesai dicatat.':'Set dibuka kembali.');if(x.done)startTimer(plans[selected].ex[i][3]==='Compound'?150:75);render()};
$('notes').onchange=e=>{const s=session();s.notes=e.target.value;save(s,'Catatan sesi tersimpan.')};
$('finish').onclick=()=>{const s=session(),sets=s.sets.flat().filter(x=>x.done);if(!sets.length){$('notice').textContent='Catat dan tandai minimal satu set terlebih dahulu.';toast('Catat minimal satu set dulu.','error');return}s.finished=true;save(s,'Sesi selesai! Catatan sudah tersimpan.');const volume=sets.reduce((n,x)=>n+Number(x.kg)*Number(x.reps),0),rated=sets.filter(x=>x.rir!==''),averageRir=rated.length?(rated.reduce((n,x)=>n+Number(x.rir),0)/rated.length).toLocaleString('id-ID',{maximumFractionDigits:1}):'—',suggestions=plans[selected].ex.map((e,i)=>({name:e[0],text:overloadSuggestion(s.sets[i],e[2],e[3])})).filter(item=>item.text);$('summary-content').innerHTML=`<div class="summary-stats"><strong>${sets.length}<span>set selesai</span></strong><strong>${volume.toLocaleString('id-ID')}<span>kg × reps</span></strong><strong>${averageRir}<span>rata-rata RIR</span></strong></div>${suggestions.length?`<h3>Sesi berikutnya</h3><ul>${suggestions.map(item=>`<li><b>${esc(item.name)}</b>: ${esc(item.text)}</li>`).join('')}</ul>`:''}`;$('session-summary').showModal();progress()};
$('summary-close').onclick=()=>$('session-summary').close();
const names=[...new Set(plans.flatMap(p=>p.ex.map(e=>e[0])))];$('exercise-filter').innerHTML=names.map(n=>`<option>${esc(n)}</option>`).join('');
function history(){const ss=Object.values(db.sessions).filter(s=>s.sets.flat().some(x=>x.done)||s.notes).sort((a,b)=>b.date.localeCompare(a.date));$('history-list').innerHTML=ss.length?ss.map(s=>{const id=`${s.date}_${s.plan}`,p=plans[s.plan],sets=s.sets.flat().filter(x=>x.done);return `<article class="history-card"><header><h3>${p.name} day</h3><span class="today">${fmt(s.date)}</span></header><p>${sets.length} set tercatat · ${s.finished?'Selesai':'Sedang berjalan'}</p><details><summary>Lihat rincian</summary>${p.ex.map((e,i)=>{const recorded=s.sets[i].filter(x=>x.done);return recorded.length?`<p><b>${esc(e[0])}</b><br>${recorded.map(x=>(x.kg||0)+' kg × '+x.reps).join(' · ')}</p>`:''}).join('')}${s.notes?`<p>${esc(s.notes)}</p>`:''}</details><button data-open="${id}">Buka catatan</button><button class="delete" data-delete="${id}">Hapus sesi</button></article>`}).join(''):'<div class="empty">Belum ada riwayat.<br>Catat set pertamamu di tab Latihan.</div>';exerciseProgress()}
function consistency(){const sessions=Object.values(db.sessions),dates=scheduledDates(localDate()),dayPlans={1:0,3:1,4:2},completed=dates.filter(value=>sessions.some(s=>s.date===value&&s.finished)).length,cells=dates.map(value=>{const d=new Date(value+'T12:00:00'),plan=plans[dayPlans[d.getDay()]],done=sessions.some(s=>s.date===value&&s.plan===dayPlans[d.getDay()]&&s.finished);return `<button type="button" class="calendar-day ${done?'trained':'missed'}" data-activity-date="${value}" aria-pressed="false"><small>${d.toLocaleDateString('id-ID',{weekday:'short'})}</small><strong>${d.toLocaleDateString('id-ID',{day:'numeric',month:'short'})}</strong><span>${plan.name}</span><em>${done?'Selesai':'Terlewat'}</em></button>`}).join('');$('consistency').innerHTML=`<div class="consistency-card"><h3>12 jadwal latihan terakhir</h3><p class="activity-copy">${completed} dari 12 jadwal selesai.</p><div class="schedule-grid">${cells}</div><div class="calendar-legend"><span><i class="trained"></i>Selesai</span><span><i class="missed"></i>Terlewat</span></div><div id="activity-detail" class="activity-detail" role="status">Tekan jadwal untuk melihat rincian.</div></div>`}
function exerciseProgress(){const name=$('exercise-filter').value,period=Number($('period-filter').value),metric=$('metric-filter').value,cutoff=period?new Date(Date.now()-period*86400000).toISOString().slice(0,10):'',rows=Object.values(db.sessions).filter(s=>!cutoff||s.date>=cutoff).sort((a,b)=>a.date.localeCompare(b.date)).flatMap(s=>{const i=plans[s.plan]?.ex.findIndex(e=>e[0]===name),summary=i>=0?exerciseSummary(s.sets[i]):null;return summary?[{date:s.date,...summary}]:[]});if(!rows.length){$('exercise-progress').innerHTML='<div class="progress-card"><p>Belum ada set tercatat untuk latihan dan periode ini.</p></div>';return}const visible=rows.slice(-12),peak=Math.max(...visible.map(r=>r[metric])),first=rows[0][metric],last=rows.at(-1)[metric],trend=last===first?'stabil':!first?`naik ke ${last}`:last>first?`naik ${Math.round((last-first)/first*100)}%`:`turun ${Math.round((first-last)/first*100)}%`,labels={volume:'volume',max:'beban maksimum',estimated1rm:'estimasi 1RM'};$('exercise-progress').innerHTML=`<div class="progress-card"><h3>${esc(name)}</h3><p>Tren ${labels[metric]} ${trend}; grafik menampilkan maksimal 12 sesi terbaru.</p><div class="chart" role="img" aria-label="Grafik ${labels[metric]} ${name}, tren ${trend}">${visible.map(r=>`<div class="chart-column"><span style="height:${Math.max(8,r[metric]/peak*100)}%" aria-label="${fmt(r.date)}: ${r[metric]}"></span><small>${fmt(r.date)}</small></div>`).join('')}</div><table><thead><tr><th>TANGGAL</th><th>BEBAN MAKS.</th><th>VOLUME</th><th>EST. 1RM</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${fmt(r.date)}</td><td>${r.max} kg</td><td>${r.volume.toLocaleString('id-ID')}</td><td>${r.estimated1rm} kg</td></tr>`).join('')}</tbody></table></div>`}
function view(name){$('train').hidden=name!=='train';$('history').hidden=name!=='history';document.querySelectorAll('[data-view]').forEach(b=>{const active=b.dataset.view===name;b.classList.toggle('active',active);b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1});if(name==='history'){history();consistency()}}
document.querySelector('nav').onclick=e=>{const b=e.target.closest('[data-view]');if(b)view(b.dataset.view)};
document.querySelector('nav').onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const buttons=[...document.querySelectorAll('[data-view]')],next=buttons[(buttons.indexOf(document.activeElement)+1)%buttons.length];next.focus();next.click()};
$('history-list').onclick=e=>{const open=e.target.closest('[data-open]'),del=e.target.closest('[data-delete]');if(open){const s=db.sessions[open.dataset.open];selected=s.plan;date=s.date;$('date').value=date;render();view('train');window.scrollTo({top:0,behavior:'smooth'})}if(del&&confirm('Hapus catatan sesi ini?')){deleted={id:del.dataset.delete,session:db.sessions[del.dataset.delete]};delete db.sessions[deleted.id];persist();clearTimeout(undoId);$('undo-delete').hidden=false;undoId=setTimeout(()=>{deleted=null;$('undo-delete').hidden=true},10000);toast('Sesi dihapus. Batalkan dalam 10 detik.');stats();history();render()}};
$('undo-delete').onclick=()=>{if(!deleted)return;clearTimeout(undoId);db.sessions[deleted.id]=deleted.session;deleted=null;persist();$('undo-delete').hidden=true;toast('Penghapusan dibatalkan.');stats();history();render()};
function download(data,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('export-data').onclick=()=>{download(db,`lift-log-${localDate()}.json`);toast('Cadangan berhasil diunduh.')};
$('import-data').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const incoming=normalizeDb(JSON.parse(await file.text()),setCounts);if(!incoming)throw new Error();download(db,`lift-log-sebelum-impor-${localDate()}.json`);const conflicts=Object.keys(incoming.sessions).filter(id=>db.sessions[id]),replace=conflicts.length&&confirm(`${conflicts.length} sesi punya tanggal dan program sama. Ganti dengan data impor? Pilih Batal untuk mempertahankan catatan saat ini.`);db=mergeDb(db,incoming,replace);if(persist()){toast('Cadangan berhasil digabungkan.');stats();history();render()}}catch(error){const message='File cadangan tidak valid. Tidak ada data yang diubah.';$('notice').textContent=message;toast(message,'error',5000)}e.target.value=''};
$('consistency').onclick=e=>{const button=e.target.closest('[data-activity-date]');if(!button)return;const sessions=Object.values(db.sessions).filter(s=>s.finished&&s.date===button.dataset.activityDate);document.querySelectorAll('[data-activity-date]').forEach(day=>day.setAttribute('aria-pressed',String(day===button)));$('activity-detail').innerHTML=sessions.length?`<strong>${fmt(button.dataset.activityDate)}</strong>${sessions.map(s=>{const sets=s.sets.flat().filter(x=>x.done),volume=sets.reduce((total,x)=>total+Number(x.kg)*Number(x.reps),0);return `<p>${esc(plans[s.plan]?.name||'Program')} · ${sets.length} set · ${volume.toLocaleString('id-ID')} kg × reps</p>`}).join('')}`:`<strong>${fmt(button.dataset.activityDate)}</strong><p>Tidak ada sesi selesai.</p>`};
$('exercise-filter').onchange=exerciseProgress;$('period-filter').onchange=exerciseProgress;$('metric-filter').onchange=exerciseProgress;
stats();render();view('train');
function networkStatus(){const offline=!navigator.onLine;$('network-status').hidden=!offline;if(offline)toast('Kamu sedang offline. Panduan yang belum pernah dibuka mungkin tidak tersedia.','error',5000)}
window.addEventListener('online',networkStatus);window.addEventListener('offline',networkStatus);networkStatus();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').then(registration=>{const offerUpdate=worker=>{if(!worker||!navigator.serviceWorker.controller)return;$('update-app').hidden=false;$('update-app').onclick=()=>worker.postMessage('SKIP_WAITING')};offerUpdate(registration.waiting);registration.addEventListener('updatefound',()=>{const worker=registration.installing;worker.addEventListener('statechange',()=>{if(worker.state==='installed')offerUpdate(worker)})});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload())}).catch(()=>toast('Mode offline belum tersedia.','error')));
